name: 'deploy-test'

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - Rogibb111/issue69

jobs:
  deploy:
    name: Deploy App To Oracle Cloud - Test
    runs-on: ubuntu-latest
    environment: 
      name: Production
      url: https://app.ski-resort-dashboard.laughingmanstudios.us.to
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.CHECKOUT_TOKEN }}
      - name: Deploy to Dokku
        uses: dokku/github-action@master
        with: 
          branch: main
          git_remote_url: 'ssh://dokku@deploy.ski-resort-dashboard.laughingmanstudios.us.to:22/ski-resort-dashboard'
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}