
name: 'deploy-test'

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - Rogibb111/issue69

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  deploy:
    name: Deploy App To Oracle Cloud - Test
    runs-on: ubuntu-latest
    environment: 
      name: Production
      url: https://app.ski-resort-dashboard.laughingmanstudios.us.to
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.CHECKOUT_TOKEN }}
      - id: string
        uses: ASzc/change-string-case-action@v5
        with:
          string: ${{ env.IMAGE_NAME }}
      - name: Echo Github Repository
        env:
            GITHUB_PACKAGE: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
        run: echo "$GITHUB_PACKAGE"
