name: 'Deploy'

# yamllint disable-line rule:truthy
on:
  workflow_run:
    workflows: [Release]
    types: [completed]
    branches: [main]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  docker:
    name: Build Docker Image and Push to Github Packages
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    permissions:
      contents: read
      packages: write
    environment:
      name: Production
      url: https://github.com/Rogibb111?tab=packages&repo_name=Ski-Resort-Dashboard
    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}
    outputs:
      tags: ${{ steps.meta.outputs.tags }}      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.PACKAGE_KEY }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
  deploy:
    name: Deploy App To Oracle Cloud
    runs-on: ubuntu-latest
    needs: docker
    environment: 
      name: Production
      url: https://app.ski-resort-dashboard.laughingmanstudios.us.to
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.CHECKOUT_TOKEN }}
      - name: Deploy to Dokku
        uses: dokku/github-action@master
        with: 
          branch: main
          git_remote_url: 'ssh://dokku@deploy.ski-resort-dashboard.laughingmanstudios.us.to:22/ski-resort-dashboard'
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          deploy_docker_image: ${{ needs.docker.outputs.tags }}
