# GitHub Action For using Semantic Release

name: Release

on: 
  push:
    branches: 
      - main
      - next
      - next-major
      - alpha
      - beta
      
jobs:
  release:
    runs-on: ubuntu-latest
    environment: 
      name: release-pipeline
      url: https://ski-resort-dashboard.herokuapp.com/
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.RELEASE_TOKEN }}

      - name: Semantic Release
        id: semantic-release
        uses: cycjimmy/semantic-release-action@v3
        with:
          semantic_version: 19.0.2
          branches: |    
            [
              '+([0-9])?(.{+([0-9]),x}).x',
              'main', 
              'next',
              'next-major',
              {
                name: 'beta', 
                prerelease: true
              }, 
              {
                name: 'alpha', 
                prerelease: true
              }
            ]
          extra_plugins: |
            @semantic-release/changelog@6.0.1
            @semantic-release/git@10.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
      - name: Print Results
        if: steps.semantic-release.outputs.new_release_published == 'true'
        run: |
          echo ${{ steps.semantic-release.outputs.new_release_version }}
          echo ${{ steps.semantic-release.outputs.new_release_major_version }}
          echo ${{ steps.semantic-release.outputs.new_release_minor_version }}
          echo ${{ steps.semantic-release.outputs.new_release_patch_version }}
      - name: Deploy To Heroku #Dummy Commit To Trigger Release
        if: steps.semantic-release.outputs.new_release_published == 'true'
        uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "ski-resort-dashboard" #Must be unique in Heroku
          heroku_email: "gibsta269@gmail.com"

  
